Quiet test run and make passing tests more obvious.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,5 +1,5 @@
-#!/bin/sh
-set -ex
+#!/bin/bash
+set -e
 cd "`dirname \"$0\"`/.."
 
 ./script/build
@@ -12,10 +12,15 @@ compile_and_run() {
   mono test/$base_name.exe
 }
 
+# runs a test file with PASS/FAIL message
+run_test() {
+  compile_and_run $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+}
+
 if [ "$1" == "" ]; then
   for test in $(ls test/*.cs); do
-    compile_and_run $test
+    run_test $test
   done
 else
-  compile_and_run $1.cs
+  run_test $1.cs
 fi
