Cleanup and use new script to simplify running files.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -4,17 +4,9 @@ cd "`dirname \"$0\"`/.."
 
 ./script/build
 
-cp build/*.dll test/
-
-compile_and_run() {
-  base_name=`basename -s .cs $1`
-  mcs -lib:build/ -reference:docraptor-all.dll test/$base_name.cs -out:test/$base_name.exe
-  mono test/$base_name.exe
-}
-
 # runs a test file with PASS/FAIL message
 run_test() {
-  compile_and_run $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+  ./script/run_csharp_file $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
 }
 
 if [ "$1" == "" ]; then
